import express, { Request, Response } from 'express';
import path from 'path';
import crypto from 'crypto';
import fs from 'fs';
import * as snarkjs from 'snarkjs';

const app = express();
app.use(express.json());
app.use(express.static('public')); // Serve the .wasm and .zkey files

// SECURITY LAYER: In-memory store for active challenges
// (In a real startup, replace this with Redis)
const activeChallenges = new Set<string>();

// Load the mathematical verification key generated by Circom
let vKey: any;
try {
    vKey = JSON.parse(fs.readFileSync('./verification_key.json', 'utf8'));
} catch (e) {
    console.error("FATAL ERROR: verification_key.json missing. Run Circom setup.");
    process.exit(1);
}

app.get('/', (req: Request, res: Response) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

// ENDPOINT 1: Issue a one-time cryptographic challenge
app.get('/api/challenge', (req: Request, res: Response) => {
    // Generate a secure, random number string (must be numeric for ZK circuits)
    const challenge = BigInt('0x' + crypto.randomBytes(8).toString('hex')).toString();
    activeChallenges.add(challenge);
    res.json({ challenge });
});

// ENDPOINT 2: Verify the zk-SNARK proof
app.post('/api/verify-human', async (req: Request, res: Response) => {
    const { proof, publicSignals } = req.body;

    if (!proof || !publicSignals || publicSignals.length === 0) {
        return res.status(400).send({ success: false, message: "Missing ZK payload." });
    }

    const clientChallenge = publicSignals[0];

    // ANTI-REPLAY ATTACK CHECK: Does this challenge exist?
    if (!activeChallenges.has(clientChallenge)) {
        return res.status(401).send({
            success: false,
            message: "SECURITY ALERT: Challenge expired or invalid. Possible replay attack detected."
        });
    }

    try {
        // ACTUAL MATH VERIFICATION: Elliptic curve pairing check
        const isProofValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

        if (isProofValid) {
            // BURN THE CHALLENGE: Ensure this proof can never be used again
            activeChallenges.delete(clientChallenge);
            return res.send({ success: true, message: "zk-SNARK Validated. Zero PII stored. Access Granted." });
        } else {
            return res.status(401).send({ success: false, message: "Mathematical proof failed." });
        }
    } catch (error) {
        console.error(error);
        return res.status(500).send({ success: false, message: "Internal verification error." });
    }
});

const PORT = 3000;
app.listen(PORT, () => {
    console.log(`🛡️ Enterprise ZKP Gateway running on http://localhost:${PORT}`);
});
